version: "3.8"
services:
    app:
        container_name: ltapp
        build:
            args:
                user: tung
                uid: 1000
            context: ./docker/laravel
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/code
        volumes:
            - .:/var/www/code
            - ./docker/laravel/php.ini:/usr/local/etc/php/php.ini-development
        networks:
            - ltweb-network

    web:
        container_name: ltweb
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/code
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ltweb-network

    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /data/postgres
        volumes:
            - ltweb-database:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - ltweb-network
        restart: unless-stopped

networks:
    ltweb-network:
        driver: bridge

volumes:
    ltweb-database:
        driver: local
